DEFAULT_HABITS = [
    {
        "goal": "focus",
        "title": "One focused block",
        "description": "Work for 25 minutes with notifications off.",
        "minutes": 25,
        "difficulty": "Easy",
    },
    {
        "goal": "focus",
        "title": "Write the first task",
        "description": "Write the single most important task before opening chat or email.",
        "minutes": 3,
        "difficulty": "Easy",
    },
    {
        "goal": "energy",
        "title": "Water before caffeine",
        "description": "Drink one full glass of water before your next tea or coffee.",
        "minutes": 2,
        "difficulty": "Easy",
    },
    {
        "goal": "energy",
        "title": "Desk reset walk",
        "description": "Take a five-minute walk away from your desk.",
        "minutes": 5,
        "difficulty": "Easy",
    },
    {
        "goal": "stress",
        "title": "Two-minute breathing reset",
        "description": "Breathe in for 4 seconds and out for 6 seconds for two minutes.",
        "minutes": 2,
        "difficulty": "Easy",
    },
    {
        "goal": "stress",
        "title": "Name the pressure",
        "description": "Write one sentence naming what is making today feel heavy.",
        "minutes": 3,
        "difficulty": "Easy",
    },
    {
        "goal": "learning",
        "title": "Ten-minute skill rep",
        "description": "Spend 10 minutes practicing one small part of a skill you care about.",
        "minutes": 10,
        "difficulty": "Medium",
    },
    {
        "goal": "learning",
        "title": "Capture one lesson",
        "description": "Write one thing you learned today and where you can reuse it.",
        "minutes": 4,
        "difficulty": "Easy",
    },
    {
        "goal": "wellbeing",
        "title": "Screen pause",
        "description": "Look away from screens and relax your shoulders for one minute.",
        "minutes": 1,
        "difficulty": "Easy",
    },
    {
        "goal": "wellbeing",
        "title": "Tomorrow's closing note",
        "description": "Write the first thing you will do tomorrow before ending work.",
        "minutes": 3,
        "difficulty": "Easy",
    },
]
